### ISSUE TITLE
`deregister` shold send DELETE http request

### ISSUE THREAD

**Issue by iblislin** [IoTtalk/iottalk-js#18]

**Comment by ghost** [comment]
在 iottalk-core-ksoy/iot/conn.py lines 251-264
CSM 在收到 `offline` 後，不是會自己送 `DELETE` request 嗎?

**Comment by iblislin** [comment]
我的版本不會

**Comment by iblislin** [comment]
而且 Python DA 裡面是有送 DELETE 的

**Comment by Ksoy** [comment]
奇怪 我剛剛看我不知道多久以前的版本是有送 delete的誒
結果一 pull 後，也沒衝突就不見了

**Comment by Ksoy** [comment]
https://github.com/IoTtalk/iottalk-js/commit/18952bd10a5c0552e7949e89cb7a5e2f33a8e64b#diff-d7405d78915b1c154fb810dfd5adfec7R168
以前有啊，好像被你重構的時候刪掉了XD

**Comment by Ksoy** [comment]
e10434d

**Comment by iblislin** [comment]
orz

**Comment by iblislin** [comment]
- 修 revision
