### ISSUE TITLE
MQTT TLS support

### ISSUE THREAD

**Issue by iblislin** [IoTtalk/iottalk-js#49]
ref: https://github.com/IoTtalk/iottalk-py/pull/48

**Comment by vava24680** [comment]
這個我用 [Dummy_Device_WebVer_for_IoTtalk_v2](https://github.com/IoTtalk/Dummy_Device_WebVer_for_IoTtalk_v2) 測過，目前的版本是有支援的 MQTT over wss 的

**Comment by iblislin** [comment]
ok
